### PR TITLE
fix erroneous error reporting with Raven

### PR DESCRIPTION
**Pull request by ericcf**
* these were all being silently ignored :-(

### CODE REVIEW

**Comment by cbrenner04** [comment]
well that's a bummer :-1:

**Comment by ericcf** [comment]
Yeah, going to fix it in other projects now.

**Comment by michaelwehrley** [comment]
:eyes: good to me!

**Comment by ericcf** [comment]
@eschlange would you mind taking a look at this?

**Comment by eschlange** [comment]
Looks good.

**Pull request merged**
