### PR TITLE
Jah batch reports

### PR DESCRIPTION
**Pull request by Tag0Mag0**

### CODE REVIEW

**Comment by Tag0Mag0** [comment]
@ericcf @eschlange @michaelwehrley @gwensmu ready to merge after Travis.

**Comment by ericcf** [comment]
@Tag0Mag0 oops, you included the reports themselves in the commit.

**Comment by Tag0Mag0** [comment]
@ericcf I thought we wanted to keep them so that we would have test report data

**Comment by ericcf** [comment]
I'd like for you to remove it from the commit and replace it with simpler dummy data. Even just the headers would be fine.

**Comment by Tag0Mag0** [comment]
@ericcf ok. Would the fixture data be ok?

**Comment by ericcf** [comment]
I don't think that would be very useful. I think the only reason to have the files here is to test that they can be downloaded. There are unit specs to test the actual report logic.

**Comment by michaelwehrley** [comment]
:+1: :camel:

**Pull request merged**
